version: '3'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: discord-bot
        env_file:
            - ./env/.env
            - ./env/.env.db
        depends_on:
            - db
        volumes:
            - ./logs:/discord-bot/src/logs

    db:
        image: postgres
        restart: unless-stopped
        container_name: discord-bot-postgres
        env_file:
            - ./env/.env.db
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
