version: '3'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: discord-bot-development
        env_file:
            - ./env/.env
            - ./env/.env.db
        environment:
            - DEGUB="1"
