version: '3'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: discord-bot-development
        env_file:
            - ./env/.env.dev
        environment:
            - DEGUB="1"
        volumes:
            - dev_bot_db:/src/sqlite.db

volumes:
    dev_bot_db:
