# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Builds bot update

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --ignore=E501,F541 --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Python Unit Tests
        run: |
          cd src
          python -m unittest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tests docker build
        run: |
          docker image build -t test_image .
